services:
  - type: web
    name: my-service
    runtime: node
    buildCommand: |
      npm install
      npx prisma generate
      npx prisma migrate deploy
      npm run build
    startCommand: node dist/server.js
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: my-database
          property: connectionString

databases:
  - name: my-database
    plan: free
