services:
  - type: web
    name: perfect-api
    env: node
    plan: free
    rootDir: .
    buildCommand: |
      npm install
      npm run build:safe
    startCommand: |
      if [ -d prisma/migrations ] && [ "$(ls -A prisma/migrations | wc -l)" -gt 0 ]; then
        npx prisma migrate deploy
      else
        npx prisma db push
      fi
      node dist/server.js
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: perfect-postgres
          property: connectionString

databases:
  - name: perfect-postgres
